# Build customization
builds:
  - id: main
    goos:
      - linux
    goarch:
      - 386
      - amd64
      - arm
      - arm64
release:
  github:
    owner: utilitywarehouse
    name: wiresteward
archives:
  - builds:
    - main
    format: binary
    files:
    - none*
