language: go

go:
  - "1.15.x"

env:
  global:
    - CGO_ENABLED=0

script:
  - go test -v ./...
  - curl -sfL https://git.io/goreleaser | sh -s -- check # check goreleaser config for deprecations

install:
  - go get ./...

# calls goreleaser
deploy:
  - provider: script
    skip_cleanup: true
    script: curl -sL https://git.io/goreleaser | bash
    on:
      tags: true
