version: 2
executorType: docker
jobs:
  test:
    docker:
      - image: circleci/golang:1.14
    working_directory: /go/src/github.com/utilitywarehouse/wiresteward
    steps:
      - checkout
      - run: go get -t ./...
      - run: go test -v ./...
  release:
    docker:
      - image: circleci/golang:1.14
    working_directory: /go/src/github.com/utilitywarehouse/wiresteward
    steps:
      - checkout
      - run: go get -t ./...
      - run: curl -sL https://git.io/goreleaser | bash
workflows:
  version: 2
  test_and_release:
    jobs:
      - test
      - release:
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /v[0-9]+(\.[0-9]+)*(-.*)*/
